### ISSUE TITLE
Tracked team is listed as opponent

### ISSUE THREAD

**Issue by twmcelroy** [SimplySynced/ha-nhl#1]
Great job on the visual card. It's why I am looking into using your custom integration. 
I was looking to set up an automation based on the score change. However, my tracked team (Dallas Stars, 'DAL') is listed as the opponent as the attribute. Today they are the home team, I'm not sure if that is why. From what I was reading, DAL should always be the "team" instead of the "opponent" for the attributes. 

```
attribution: Data provided by ESPN  
date: 2022-01-19T01:30Z
puck_drop: null
period: 2
clock: 2:27
venue: American Airlines Center
location: Dallas, TX
tv_network: ESPN+
odds: null
overunder: null
team_abbr: MTL
team_id: 10
team_name: Canadiens
team_record: 7-25-5
team_homeaway: away
team_logo: https://a.espncdn.com/i/teamlogos/nhl/500/scoreboard/mtl.png
team_colors: #a3121b, #001e62
team_score: 2
opponent_abbr: DAL
opponent_id: 9
opponent_name: Stars
opponent_record: 18-15-2
opponent_homeaway: home
opponent_logo: https://a.espncdn.com/i/teamlogos/nhl/500/scoreboard/dal.png
opponent_colors: #00704a, #8c9192
opponent_score: 1
last_update: 2022-01-18 21:12:59-06:00
icon: mdi:hockey-sticks
friendly_name: NHL
```

Because of this, my automation doesn't trigger for the right team.

**Comment by SimplySynced** [comment]
Hello, 

It definately should have the Stars as the team and not the opponent.  I see it happened locally as well, not sure when that happened but I'll work on this issue and get an update to fix it.

**Comment by SimplySynced** [comment]
Please update to the latest release and confirm that the sensor is correctly displaying your tracked team as the team and not the opponent.  The latest release is found here.  https://github.com/SimplySynced/ha-nhl/releases/tag/v0.2

**Comment by twmcelroy** [comment]
Yes the update worked. Thank you!
Do you have any ideas on automations for goals? There is another NHL customization under HACS but I've enjoyed your visualizations and what you are exposing.

**Comment by SimplySynced** [comment]
I have not been able to figure out the automation part just yet.  I know on the original NFL thread on the Home Assistant community there are some automations people used for scores.  They should perhaps be usable with adjustments for NHL.  I have not done any testing yet but I plan on doing that soon.  Also some sensor updates as well.
