### ISSUE TITLE
Sensor unavailable 

### ISSUE THREAD

**Issue by dnestico** [SimplySynced/ha-nhl#2]
I did the setup correctly and is it supposed to state "unavailable" because season hasn't started yet?

<img width="501" alt="Screen Shot 2022-08-24 at 4 13 44 PM" src="https://user-images.githubusercontent.com/3034555/186514536-0cbe0985-8648-4e3e-9993-0eb63684e464.png">
<img width="142" alt="Screen Shot 2022-08-24 at 4 13 36 PM" src="https://user-images.githubusercontent.com/3034555/186514540-e974cb7e-c02c-458c-b678-fd6c7c13cbd9.png">

**Comment by SimplySynced** [comment]
I just tried that within my local instance and I am populated with some information.  I see they are playing Ottawa.  If you look at your HA logs and search for NHL can you see if there is an error and if so what it is.  If it doesn't see the team in the score page it should look for the actual teams page.  I'm curious what happened in your instance.

**Comment by eboline** [comment]
This integration is great!

Everything was working fine, but after having worked perfectly for a week, I looked today and see my "sensor.wild" is showing unavailable.  I tried searching the logs and all I am seeing is that the sensor became unavailable 3 hours ago.

What additional information can I provide to help troubleshoot?

**Comment by eboline** [comment]
> 

Sensor is working now.  Strange.

**Comment by ajakubek80** [comment]
I also have the same problem.
![image](https://user-images.githubusercontent.com/51712504/194723110-e03d6696-2765-4b72-9fb5-a846c5037218.png)
![image](https://user-images.githubusercontent.com/51712504/194723143-0e1a8702-a110-40dc-a333-aba3b524c053.png)
![image](https://user-images.githubusercontent.com/51712504/194723257-1165a801-dd0e-490d-b5ee-2418868169c8.png)
Another sensor Tampa Bay is working fine.
![image](https://user-images.githubusercontent.com/51712504/194723351-abc79148-dbf4-4c19-84e5-987fd9b74388.png)

**Comment by SimplySynced** [comment]
Hey guys, I found that the issue was due to some of the values not being available for preseason games.  I've just released a new version.  Can you give it an update and confirm it works.  If it doesn't, in your HA logs search for ha_nhl and it should tell you any possible errors and I can get it sorted.

**Comment by ajakubek80** [comment]
Thank you. Now it is working. 

![image](https://user-images.githubusercontent.com/51712504/194772345-eb04df4e-2ab2-4e21-98c7-59e4acffed5d.png)

**Comment by SimplySynced** [comment]
Excellent!  Thanks guys.  Always open for any input or suggestions.
