### ISSUE TITLE
Sensor not correct

### ISSUE THREAD

**Issue by eboline** [SimplySynced/ha-nhl#3]
How often and when does the sensor created update? 

I have my integration set up for the Wild (sensor.wild).  The sensor is currently stating that their next game is against Bos on 10-22-22 at TD Garden, however they have a game on 10-13-22 at Xcel Energy Center against the New York Rangers.  Why  wouldn't it show the information for the 10-13-22 game?

For reference, I also have the NHL API Custom Component through HACS set up as well (https://github.com/JayBlackedOut/hass-nhlapi/releases/v0.10.2).  I'm currently using this for "real-time" goal notifications for automations.  Ultimately, it is only used for that and is not pulling any data from the created sensor (sensor.nhl_sensor) for the lovelace card.  When I look at the state and attribute for this sensor in Developer Tools, it shows the correct information.  Game is 10-13-22 and correct opponent information and so forth.

Any ideas?

**Comment by SimplySynced** [comment]
The sensor during the game is checking every 5 seconds during game time.  When its not within a game it will be every 10mins for checking.  Are you trying to use the other sensor with the NHL Card created  by myself?  It should find the correct game.  I can test for the Wild locally and see if I get the same issue.

**Comment by eboline** [comment]
I'm using your sensor with your card.  The nhl-api sensor I'm currently only using for trigger a goal event.

Your sensor showed correctly yesterday (game day) and this morning, but now it is showing a game on Saturday against Boston again.  Their next game is against the Kings this coming Saturday.

sensor.wild shows:

![sensor wild](https://user-images.githubusercontent.com/74580331/195954397-e4bd5490-7666-42ea-89ca-10bc94757d71.jpg)

sensor.nhl shows:
![sensor nhl](https://user-images.githubusercontent.com/74580331/195954260-4b0d142e-17ed-4b48-b98c-3287f31e3882.jpg)

**Comment by SimplySynced** [comment]
Thanks for the response!  Right off the bat it looks to me that they are using a different URL.  This sensor should be going to the following URL which is https://site.api.espn.com/apis/site/v2/sports/hockey/nhl/teams/min when it is not showing in the days scoreboard API with all the games of that day.  You can see that in this URL that is exactly what they have which is the game with the Bruins.  I do see they do have a closer game.  The plugin you mentioned uses a python plugin that uses a different URL where it is getting its information from. Very interesting the ESPN URL is wrong.  Let me look and see about these other API URLs.

**Comment by eboline** [comment]
Thanks so much!  I look forward to hearing back!

**Comment by SimplySynced** [comment]
As an update.  It looks like the Teams endpoint that was being used for the next game is only showing the next home game.  I have started to implement the new endpoint that the other plugin is using.  Looking at an ETA by Friday.

**Comment by eboline** [comment]
Thanks for the update, but I don't totally understand the explanation.

"It looks like the Teams endpoint that was being used for the next game is only showing the next home game."  The game showing on the card right now is an away game for the Wild so was it showing the next away game?  The Wild start the season with 4 straight home games and the Bruins game is their first away game of the season.

Maybe it's irrelevant if you change the end point, just trying to learn and understand as I go here.  I really appreciate you spending the time looking into this!

**Comment by SimplySynced** [comment]
Apologies on the delay.  So it looks like where I was pulling the next game wasn't showing the correct next game.  From what I initially saw it looked as if it would pull the team next home game but it seems you said it wasn't.  However it seems in the past week ESPN has fixed where I am pulling it from originally.  Can you confirm it has been working for you?  I can use the same endpoint at that other one but some of the data is not there that we get with the ESPN one it looks like.  Not without reaching multiple endpoints.

**Comment by eboline** [comment]
No worries!  This has been working fine for me now!  I really appreciate you taking the time to look at this!

**Comment by SimplySynced** [comment]
Absolutely!
